name: aviapoint_server
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  shelf: ^1.4.2
  async: ^2.5.0
  collection: ^1.15.0
  http_parser: ^4.1.0
  path: ^1.8.0
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0
  shelf_router: ^1.1.4
  shelf_open_api: ^1.1.0
  shelf_swagger_ui: ^1.0.0+2
  shelf_static: ^1.1.3
  shelf_cors_headers: ^0.1.5
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  postgres: ^3.4.2
  uuid: ^4.5.1
  logger: ^2.5.0
  get_it: ^7.6.0
  dio: ^5.8.0+1
  jwt_decoder: ^2.0.1
  talker: ^3.1.0
  http: ">=0.13.0 <2.0.0"
  jose: ^0.3.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
  shelf_router_generator: ^1.0.6
  build_runner: ^2.4.6
  shelf_open_api_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pdf/
    # - assets/video/video_for_students.mp4
    - assets/photo/
    - public/
